name: 'Test Webpage'
description: 'So much potential'
tagline: 'yada yada'
url: 'http://iris-robedeaux.github.io'
baseurl: '/sampleWebsiteNew'
paginate: 10

markdown: kramdown
highlighter: rouge

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
# permalink: /:year/:month/:title/
relative_permalinks: false

# About/contact
author: Iris Robedeaux

# GitHub
github:
  repo: github.com/iris-robedeaux/sampleWebsiteNew

# Feed Stuff
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
